// Generated by gencpp from file gnss_comm/GnssSsrPhaseBiases.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSSSRPHASEBIASES_H
#define GNSS_COMM_MESSAGE_GNSSSSRPHASEBIASES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_comm/GnssSsrPhaseBias.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssSsrPhaseBiases_
{
  typedef GnssSsrPhaseBiases_<ContainerAllocator> Type;

  GnssSsrPhaseBiases_()
    : header()
    , biases()  {
    }
  GnssSsrPhaseBiases_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , biases(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gnss_comm::GnssSsrPhaseBias_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gnss_comm::GnssSsrPhaseBias_<ContainerAllocator> >> _biases_type;
  _biases_type biases;





  typedef boost::shared_ptr< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> const> ConstPtr;

}; // struct GnssSsrPhaseBiases_

typedef ::gnss_comm::GnssSsrPhaseBiases_<std::allocator<void> > GnssSsrPhaseBiases;

typedef boost::shared_ptr< ::gnss_comm::GnssSsrPhaseBiases > GnssSsrPhaseBiasesPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssSsrPhaseBiases const> GnssSsrPhaseBiasesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.biases == rhs.biases;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6159b3ab70f3feffd59baf141fb2772d";
  }

  static const char* value(const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6159b3ab70f3feffULL;
  static const uint64_t static_value2 = 0xd59baf141fb2772dULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssSsrPhaseBiases";
  }

  static const char* value(const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"GnssSsrPhaseBias[] biases  # SSR phase biases\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gnss_comm/GnssSsrPhaseBias\n"
"string prn        # Satellite PRN number\n"
"uint16 week       # GPS week, SSR message\n"
"float64 tow       # GPS time of week, SSR message\n"
"uint32 iod        # Issue of data, SSR message\n"
"uint8 isdpb       # If differenced\n"
"float64 udi       # SSR update interval\n"
"string[] phase    # Phase indicators\n"
"float64[] bias    # Phase biases\n"
;
  }

  static const char* value(const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.biases);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssSsrPhaseBiases_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssSsrPhaseBiases_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "biases[]" << std::endl;
    for (size_t i = 0; i < v.biases.size(); ++i)
    {
      s << indent << "  biases[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_comm::GnssSsrPhaseBias_<ContainerAllocator> >::stream(s, indent + "    ", v.biases[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSSSRPHASEBIASES_H
