// Generated by gencpp from file gnss_comm/GnssObservations.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSOBSERVATIONS_H
#define GNSS_COMM_MESSAGE_GNSSOBSERVATIONS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_comm/GnssObservation.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssObservations_
{
  typedef GnssObservations_<ContainerAllocator> Type;

  GnssObservations_()
    : header()
    , observations()  {
    }
  GnssObservations_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , observations(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gnss_comm::GnssObservation_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gnss_comm::GnssObservation_<ContainerAllocator> >> _observations_type;
  _observations_type observations;





  typedef boost::shared_ptr< ::gnss_comm::GnssObservations_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssObservations_<ContainerAllocator> const> ConstPtr;

}; // struct GnssObservations_

typedef ::gnss_comm::GnssObservations_<std::allocator<void> > GnssObservations;

typedef boost::shared_ptr< ::gnss_comm::GnssObservations > GnssObservationsPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssObservations const> GnssObservationsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssObservations_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssObservations_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssObservations_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssObservations_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.observations == rhs.observations;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssObservations_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssObservations_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssObservations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssObservations_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssObservations_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssObservations_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssObservations_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssObservations_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssObservations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9fa545dbe3bd92fe626968338708f3c5";
  }

  static const char* value(const ::gnss_comm::GnssObservations_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9fa545dbe3bd92feULL;
  static const uint64_t static_value2 = 0x626968338708f3c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssObservations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssObservations";
  }

  static const char* value(const ::gnss_comm::GnssObservations_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssObservations_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"GnssObservation[] observations   # Observations of each satellites\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gnss_comm/GnssObservation\n"
"string prn        # Satellite PRN number\n"
"uint16 week       # GPS week\n"
"float64 tow       # GPS time of week\n"
"float64[] SNR      # Signal strengths\n"
"uint8[] LLI       # Loss of lock indicators\n"
"string[] code     # Code indicators\n"
"float64[] L       # Carrier phase cycles\n"
"float64[] P       # Pseudoranges\n"
"float64[] D       # Dopplers\n"
;
  }

  static const char* value(const ::gnss_comm::GnssObservations_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssObservations_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.observations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssObservations_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssObservations_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssObservations_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "observations[]" << std::endl;
    for (size_t i = 0; i < v.observations.size(); ++i)
    {
      s << indent << "  observations[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_comm::GnssObservation_<ContainerAllocator> >::stream(s, indent + "    ", v.observations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSOBSERVATIONS_H
