// Generated by gencpp from file gnss_comm/GnssEphemMsgarray.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSEPHEMMSGARRAY_H
#define GNSS_COMM_MESSAGE_GNSSEPHEMMSGARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_comm/GnssEphemMsg.h>
#include <gnss_comm/GnssGloEphemMsg.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssEphemMsgarray_
{
  typedef GnssEphemMsgarray_<ContainerAllocator> Type;

  GnssEphemMsgarray_()
    : header()
    , ephem()
    , gloephem()  {
    }
  GnssEphemMsgarray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ephem(_alloc)
    , gloephem(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gnss_comm::GnssEphemMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gnss_comm::GnssEphemMsg_<ContainerAllocator> >> _ephem_type;
  _ephem_type ephem;

   typedef std::vector< ::gnss_comm::GnssGloEphemMsg_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gnss_comm::GnssGloEphemMsg_<ContainerAllocator> >> _gloephem_type;
  _gloephem_type gloephem;





  typedef boost::shared_ptr< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> const> ConstPtr;

}; // struct GnssEphemMsgarray_

typedef ::gnss_comm::GnssEphemMsgarray_<std::allocator<void> > GnssEphemMsgarray;

typedef boost::shared_ptr< ::gnss_comm::GnssEphemMsgarray > GnssEphemMsgarrayPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssEphemMsgarray const> GnssEphemMsgarrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ephem == rhs.ephem &&
    lhs.gloephem == rhs.gloephem;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "31054b3280a005cf30c1076c7645b85e";
  }

  static const char* value(const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x31054b3280a005cfULL;
  static const uint64_t static_value2 = 0x30c1076c7645b85eULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssEphemMsgarray";
  }

  static const char* value(const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"GnssEphemMsg[] ephem             # GPS, BDS, Galileo ephemeris of each satellites\n"
"GnssGloEphemMsg[] gloephem \n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gnss_comm/GnssEphemMsg\n"
"# This message contains GPS, Galileo and BeiDou ephemeris data\n"
"\n"
"uint32 sat\n"
"GnssTimeMsg ttr\n"
"GnssTimeMsg toe\n"
"GnssTimeMsg toc\n"
"float64 toe_tow\n"
"uint32 week\n"
"uint32 iode\n"
"uint32 iodc\n"
"uint32 health\n"
"uint32 code\n"
"float64 ura\n"
"float64 A\n"
"float64 e\n"
"float64 i0\n"
"float64 omg\n"
"float64 OMG0\n"
"float64 M0\n"
"float64 delta_n\n"
"float64 OMG_dot\n"
"float64 i_dot\n"
"float64 cuc\n"
"float64 cus\n"
"float64 crc\n"
"float64 crs\n"
"float64 cic\n"
"float64 cis\n"
"float64 af0\n"
"float64 af1\n"
"float64 af2\n"
"float64 tgd0\n"
"float64 tgd1\n"
"float64 A_dot\n"
"float64 n_dot\n"
"================================================================================\n"
"MSG: gnss_comm/GnssTimeMsg\n"
"# This message contains GNSS time expressed in the form of \n"
"# GNSS week number and time of week(in seconds)\n"
"\n"
"uint32 week\n"
"float64 tow\n"
"================================================================================\n"
"MSG: gnss_comm/GnssGloEphemMsg\n"
"# This message contains GLONASS ephemeris data\n"
"\n"
"uint32 sat\n"
"GnssTimeMsg ttr\n"
"GnssTimeMsg toe\n"
"int32  freqo\n"
"uint32 iode\n"
"uint32 health\n"
"uint32 age\n"
"float64 ura\n"
"float64 pos_x\n"
"float64 pos_y\n"
"float64 pos_z\n"
"float64 vel_x\n"
"float64 vel_y\n"
"float64 vel_z\n"
"float64 acc_x\n"
"float64 acc_y\n"
"float64 acc_z\n"
"float64 tau_n\n"
"float64 gamma\n"
"float64 delta_tau_n\n"
;
  }

  static const char* value(const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ephem);
      stream.next(m.gloephem);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssEphemMsgarray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssEphemMsgarray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ephem[]" << std::endl;
    for (size_t i = 0; i < v.ephem.size(); ++i)
    {
      s << indent << "  ephem[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_comm::GnssEphemMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.ephem[i]);
    }
    s << indent << "gloephem[]" << std::endl;
    for (size_t i = 0; i < v.gloephem.size(); ++i)
    {
      s << indent << "  gloephem[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_comm::GnssGloEphemMsg_<ContainerAllocator> >::stream(s, indent + "    ", v.gloephem[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSEPHEMMSGARRAY_H
