// Generated by gencpp from file gnss_comm/GnssIonosphereParameter.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSIONOSPHEREPARAMETER_H
#define GNSS_COMM_MESSAGE_GNSSIONOSPHEREPARAMETER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssIonosphereParameter_
{
  typedef GnssIonosphereParameter_<ContainerAllocator> Type;

  GnssIonosphereParameter_()
    : header()
    , type(0)
    , parameters()  {
    }
  GnssIonosphereParameter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , parameters(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _type_type;
  _type_type type;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _parameters_type;
  _parameters_type parameters;





  typedef boost::shared_ptr< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> const> ConstPtr;

}; // struct GnssIonosphereParameter_

typedef ::gnss_comm::GnssIonosphereParameter_<std::allocator<void> > GnssIonosphereParameter;

typedef boost::shared_ptr< ::gnss_comm::GnssIonosphereParameter > GnssIonosphereParameterPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssIonosphereParameter const> GnssIonosphereParameterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.parameters == rhs.parameters;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4f00c6b15e1d361b167a522576838278";
  }

  static const char* value(const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4f00c6b15e1d361bULL;
  static const uint64_t static_value2 = 0x167a522576838278ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssIonosphereParameter";
  }

  static const char* value(const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"uint8 type            # Parameter type (0:GPS,1:BDS,2:Galileo)\n"
"float64[] parameters  # Parameters\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.parameters);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssIonosphereParameter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssIonosphereParameter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "parameters[]" << std::endl;
    for (size_t i = 0; i < v.parameters.size(); ++i)
    {
      s << indent << "  parameters[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.parameters[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSIONOSPHEREPARAMETER_H
