// Generated by gencpp from file gnss_comm/GnssSsrEphemerides.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSSSREPHEMERIDES_H
#define GNSS_COMM_MESSAGE_GNSSSSREPHEMERIDES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <gnss_comm/GnssSsrEphemeris.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssSsrEphemerides_
{
  typedef GnssSsrEphemerides_<ContainerAllocator> Type;

  GnssSsrEphemerides_()
    : header()
    , corrections()  {
    }
  GnssSsrEphemerides_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , corrections(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::gnss_comm::GnssSsrEphemeris_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::gnss_comm::GnssSsrEphemeris_<ContainerAllocator> >> _corrections_type;
  _corrections_type corrections;





  typedef boost::shared_ptr< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> const> ConstPtr;

}; // struct GnssSsrEphemerides_

typedef ::gnss_comm::GnssSsrEphemerides_<std::allocator<void> > GnssSsrEphemerides;

typedef boost::shared_ptr< ::gnss_comm::GnssSsrEphemerides > GnssSsrEphemeridesPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssSsrEphemerides const> GnssSsrEphemeridesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.corrections == rhs.corrections;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4d2051d76baaed52944bc5181382d27";
  }

  static const char* value(const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4d2051d76baaed5ULL;
  static const uint64_t static_value2 = 0x2944bc5181382d27ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssSsrEphemerides";
  }

  static const char* value(const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"GnssSsrEphemeris[] corrections  # SSR ephemeris corrections\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: gnss_comm/GnssSsrEphemeris\n"
"string prn        # Satellite PRN number\n"
"uint16 week       # GPS week, SSR message\n"
"float64 tow       # GPS time of week, SSR message\n"
"uint32 iod        # Issue of data, SSR message\n"
"float64 udi       # SSR update interval\n"
"uint8 iode        # Issue of data, ephemeris\n"
"uint32 iodcrc     # Issue of data crc for BDS\n"
"uint8 refd        # Sat ref datum (0:ITRF,1:regional)\n"
"float64[] deph    # Delta orbit {radial,along,cross}\n"
"float64[] ddeph   # Dot delta orbit {radial,along,cross}\n"
"float64[] dclk    # Delta clock {c0,c1,c2}\n"
;
  }

  static const char* value(const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.corrections);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssSsrEphemerides_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssSsrEphemerides_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "corrections[]" << std::endl;
    for (size_t i = 0; i < v.corrections.size(); ++i)
    {
      s << indent << "  corrections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::gnss_comm::GnssSsrEphemeris_<ContainerAllocator> >::stream(s, indent + "    ", v.corrections[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSSSREPHEMERIDES_H
