// Generated by gencpp from file gnss_comm/GnssAntennaPosition.msg
// DO NOT EDIT!


#ifndef GNSS_COMM_MESSAGE_GNSSANTENNAPOSITION_H
#define GNSS_COMM_MESSAGE_GNSSANTENNAPOSITION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gnss_comm
{
template <class ContainerAllocator>
struct GnssAntennaPosition_
{
  typedef GnssAntennaPosition_<ContainerAllocator> Type;

  GnssAntennaPosition_()
    : header()
    , pos()  {
    }
  GnssAntennaPosition_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pos(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _pos_type;
  _pos_type pos;





  typedef boost::shared_ptr< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> const> ConstPtr;

}; // struct GnssAntennaPosition_

typedef ::gnss_comm::GnssAntennaPosition_<std::allocator<void> > GnssAntennaPosition;

typedef boost::shared_ptr< ::gnss_comm::GnssAntennaPosition > GnssAntennaPositionPtr;
typedef boost::shared_ptr< ::gnss_comm::GnssAntennaPosition const> GnssAntennaPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.pos == rhs.pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator1> & lhs, const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gnss_comm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95ea387fcd600af768ebc52266faf8b7";
  }

  static const char* value(const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95ea387fcd600af7ULL;
  static const uint64_t static_value2 = 0x68ebc52266faf8b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gnss_comm/GnssAntennaPosition";
  }

  static const char* value(const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header \n"
"float64[] pos    # Station position in ECEF\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GnssAntennaPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gnss_comm::GnssAntennaPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gnss_comm::GnssAntennaPosition_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pos[]" << std::endl;
    for (size_t i = 0; i < v.pos.size(); ++i)
    {
      s << indent << "  pos[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.pos[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GNSS_COMM_MESSAGE_GNSSANTENNAPOSITION_H
