(cl:in-package gnss_comm-msg)
(cl:export '(PRN-VAL
          PRN
          WEEK-VAL
          WEEK
          FRQ-VAL
          FRQ
          IODE-VAL
          IODE
          SVH-VAL
          SVH
          AGE-VAL
          AGE
          TOE-VAL
          TOE
          TOF-VAL
          TOF
          POS-VAL
          POS
          VEL-VAL
          VEL
          ACC-VAL
          ACC
          TAUN-VAL
          TAUN
          GAMN-VAL
          GAMN
          DTAUN-VAL
          DTAUN
))