(cl:in-package gnss_comm-msg)
(cl:export '(PRN-VAL
          PRN
          WEEK-VAL
          WEEK
          SVA-VAL
          SVA
          CODE-VAL
          CODE
          IODE-VAL
          IODE
          IODC-VAL
          IODC
          SVH-VAL
          SVH
          TOC-VAL
          TOC
          IDOT-VAL
          IDOT
          CRS-VAL
          CRS
          DELN-VAL
          DELN
          M0-VAL
          M0
          CUC-VAL
          CUC
          E-VAL
          E
          CUS-VAL
          CUS
          A-VAL
          A
          TOES-VAL
          TOES
          CIC-VAL
          CIC
          OMG0-VAL
          OMG0
          CIS-VAL
          CIS
          I0-VAL
          I0
          CRC-VAL
          CRC
          OMG-VAL
          OMG
          OMGD-VAL
          OMGD
          TGD-VAL
          TGD
          F2-VAL
          F2
          F1-VAL
          F1
          F0-VAL
          F0
))